CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=y

# BLE configs
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
CONFIG_ZMK_PM_SOFT_OFF=y

# Enable mouse keys
CONFIG_ZMK_MOUSE=y
CONFIG_INPUT=y
CONFIG_GPIO=y

# Enable I2C for Cirque Glidepoint
CONFIG_I2C=y
CONFIG_PINCTRL=y
CONFIG_INPUT_PINNACLE=y

# Enable USB Logging
CONFIG_ZMK_USB_LOGGING=y